application: think-far
version: 1-2-0
runtime: python
api_version: 1

handlers:

- url: /css
  static_dir: css

- url: /images
  static_dir: images

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: .*
  script: app.py
